function [fitresult, gof] = createFit1(x, y)
%CREATEFIT2(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Sep-2014 13:32:54

%
% David Willingham, MathWorks
% Copyright 2015 The MathWorks, Inc.
%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'sin6' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.Normalize = 'on';
opts.StartPoint = [19082842.9368587 0.919276150445679 1.52167245384212 8124592.51781895 1.83855230089136 -1.5820359940459 1598873.44159063 3.67710460178272 1.60140065701916 632160.365786889 5.51565690267407 -1.50965856261744 639442.422996091 16.5469707080222 1.96166262591763 627414.038390401 33.0939414160444 2.2259342344021];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on


